version: '3.9'

services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: agendaweb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: backend_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/agendaweb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend-network
      - shared-network

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    networks:
      - frontend-network
      - shared-network
    depends_on:
      - backend

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
  shared-network:
    driver: bridge

volumes:
  mysql_data: