services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: agendaweb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    image: matheuxmoraes/backend-app:latest
    container_name: backend_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/agendaweb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend-network
      - shared-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    image: matheuxmoraes/frontend-app:latest
    container_name: frontend_container
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    ports:
      - "3000:3000"
    networks:
      - frontend-network
      - shared-network
    depends_on:
      backend:
        condition: service_healthy

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_container
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shared-network
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    depends_on:
      backend:
        condition: service_started


networks:
  backend-network:
    driver: bridge
    name: backend-network
  frontend-network:
    driver: bridge
    name: frontend-network
  shared-network:
    driver: bridge
    name: shared-network

volumes:
  mysql_data:
  jenkins_home: