apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:latest
          command:
            - sh
            - "-c"
            - |
              until nc -z -v -w 10 mysql-svc:3306; do
              echo "waiting for mysql...";
              sleep 5;
              done
      containers:
        - name: backend
          image: matheuxmoraes/backend-app:latest

          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: mysql-svc
            - name: DATABASE_PORT
              value: "3306"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-svc:3306/agendaweb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: dev
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
  selector:
    app: backend