global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: 'api/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets: ['backend-svc.dev.svc.cluster.local:8080']